### ISSUE TITLE
Installation instructions from source

### ISSUE THREAD

**Issue by rinigus** [valhalla/valhalla-docs#113]
To be able to build and run valhalla stack on local machine, would be great to have installation instructions that are applicable to non-supported distributions. Right now, its probably possible but relatively hard to see which of the components has to be installed and in which sequence. While README has a section "Building and Running Valhalla" [ https://github.com/valhalla/tools ], it would be great to get instructions that don't rely on apt-get. In addition, I suggest to add these instructions under valhalla-docs and refer to them from valhalla repo.

Kind regards,

rinigus

**Comment by kevinkreiser** [comment]
we have instructions in that same readme for building from source. and we list the debian packages that are required to do so in the apt-get line. what would you suggest so that we could help more people build this themselves? i think its reasonable to expect that there is some package manager on the target platform. we arent going to give instructions on how to compile all the dependencies as well.

i like your suggestion of moving this into to this repository its something we just havent gotten around to. what would you suggest in terms of additional documentation for getting the dependencies? whats your target platform. i would say the most common one we've heard so far is people using brew on macs and I know next to nothing about it so we'd need this information in the form of a pr from someone who has a clue about it :smile: (ie can confirm it works)

**Comment by rinigus** [comment]
I see, I managed to miss it since it was commented out (I guess it is natural to skip the commented out text). So, maybe you could split it into two subsections: one with the installation from binary (ppa) and the second one (with the same instructions as you have for building, but not commented out). That might save your time by avoiding silly issues as this one :) 

Target platform: at present it was Gentoo with an idea of trying it on mobile (Sailfish). It would depend on whether this beast is suitable for mobile at all (RAM and [in smaller extend] HDD requirements).

**Comment by kevinkreiser** [comment]
Yep we recently did some update that allow it to use even less ram. And in fact I'm going to add those to the instructions as well (basically we memory map the data as a tar file, saves a lot of memory and removes the need for us to manage cache). In terms of disk space the planet is about 50gb but if you know the area you are interested in it can be much much smaller.

**Comment by rinigus** [comment]
Closing as a stale and not critical issue.

As such, using Valhalla on desktop and Sailfish mobile with great success!
