### ISSUE TITLE
Unclear steps

### ISSUE THREAD

**Issue by KathleenLD** [valhalla/valhalla-docs#13]
In this issue I'm just adding some potential wording changes based on what tripped me up along the way. Feel free to ignore.

> Change `<my routing mode>` to `auto` to perform routing by automobile. `js router: L.Routing.valhalla('valhalla-xxxxxx', 'auto'), `

The 2nd half of that suggestion is unclear. Because of the example text below I see what you're trying to get me to do, but I'm not exactly sure what to make of that line.

---
From Rhonda - this is the markdown rendering issue.

**Comment by KathleenLD** [comment]
Oh. I see now that it's showing what that line in my code is supposed to look like... Had you meant for `js router:` to start a new line, maybe?

**Comment by KathleenLD** [comment]
> Replace the `L.Routing.control` block with the following code to initialize 

I would change this to 

> Replace the **code within** the L.Routing.control block with the following code to initialize

**Comment by KathleenLD** [comment]
> Inside the `<script>` tag, but below what you added in the previous section

I would change this to 

> Inside the `<script>` tag, below what you added in the previous section

This sounds silly, but that "but" tripped me up, and I ended up putting the code in the wrong place.

**Comment by rmglennon** [comment]
This line is a markdown rendering problem because it should have a line break. If it rendered properly, then the js wouldn't actually show (it's there to tell the markdown to do JavaScript code highlighting). Investigating why GitHub shows it like this...looks fine in the raw markdown, Atom, and on dev...

Change <my routing mode> to auto to perform routing by automobile. js router: L.Routing.valhalla('valhalla-xxxxxx', 'auto'),

**Comment by rmglennon** [comment]
Added note to the commit: https://github.com/valhalla/valhalla-docs/commit/9428c1eb3a2ede646ed19c800753294e0ed32920
