### ISSUE TITLE
Improvement: Add max speed road parameter

### ISSUE THREAD

**Issue by costales** [valhalla/valhalla-docs#29]
Hi!

I'd be a good improvement to return the max. speed road into the parameters from the API :)

Best regards!

**Comment by dnesbitt61** [comment]
Do you mean in the response? Since the response is at a maneuver level (not per graph edge) this isn't so useful. On a long maneuver where max speed changes there is no way to send back information that will tell you the max. speed at any point along the maneuver. We plan to support this via tile downloads so that mobile apps can have access to all graph information in a region or along a route.

**Comment by costales** [comment]
> Do you mean in the response?

Yes :) Then I could set a panel with that data and sound indications.

Thanks anyway :)
